name: Code Quality Checks
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: '8.1.0' # specify the version of pnpm you need

      - name: Install dependencies
        run: pnpm install

      - name: Run ESLint
        run: pnpm run lint # assuming "lint" script in package.json runs ESLint

      - name: Run Prettier
        run: pnpm run format # assuming "format" script in package.json runs Prettier
