name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-linters:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: '8.1.0' # specify the version of pnpm you need
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '18.14.0' # replace with your Node.js version
      - run: pnpm i
      - uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true
